#!/usr/bin/env python3
"""Convergence study of selected sections with full neighboring sweep context."""

from __future__ import annotations

import argparse
import hashlib
import json
import pickle
import time
from dataclasses import asdict, replace
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import trimesh
from generate_tube_only import export_surface

from plume_advanced.evaluation.local_geometry import (
    contour_distance,
    local_geometry,
    section_contour,
)
from plume_advanced.evaluation.metrics.morphometry import contour_morphometry


def study_identity(checkpoint, config, anchor):
    digest = hashlib.sha256()
    with checkpoint.open("rb") as stream:
        while block := stream.read(1024 * 1024):
            digest.update(block)
    return {
        "checkpoint_sha256": digest.hexdigest(),
        "geometry_config": asdict(config),
        "lattice_origin_m": list(map(float, anchor)),
        "region_policy": "half width along normal + 2 m along tangent + 1 m axis-aligned margin",
        "local_meshing_revision": 1,
    }


def plot_convergence(folder, index, resolutions, contours):
    fig = plt.figure(figsize=(10, 3))
    ax = fig.add_axes((0.08, 0.23, 0.9, 0.38))
    for h, q in zip(resolutions, contours):
        ax.plot(q[:, 0], q[:, 1], label=f"{h:g} m grid")
    ax.set(aspect="equal", xlabel="Across passage (m)", ylabel="Vertical offset (m)")
    fig.suptitle(f"Shallow section {index}: full network context", y=0.97)
    fig.legend(
        *ax.get_legend_handles_labels(),
        ncol=len(resolutions),
        loc="upper center",
        bbox_to_anchor=(0.5, 0.89),
        fontsize=9,
    )
    ax.grid(alpha=0.15)
    fig.savefig(folder / "convergence.png", dpi=140)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--checkpoint",
        required=True,
        type=Path,
        help="Trusted local checkpoint generated by this project; never an untrusted pickle",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--samples", default="197,804,196,203,806,195")
    parser.add_argument("--resolutions", default="0.2,0.1,0.05,0.025,0.0125")
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Reuse checked exports only when the saved plan matches",
    )
    parser.add_argument("--max-voxels", type=int, default=100_000_000)
    args = parser.parse_args()
    network, sections, baseline = pickle.loads(args.checkpoint.read_bytes())
    samples = [s for f in sections.segment_fields for s in f.samples]
    config, anchor = baseline.config, np.asarray(baseline.voxel_grid.origin)
    del baseline
    resolutions = list(map(float, args.resolutions.split(",")))
    if len(resolutions) < 2 or any(a <= b for a, b in zip(resolutions, resolutions[1:])):
        parser.error("Provide at least two strictly decreasing positive resolutions")
    if not np.all(np.isfinite(resolutions)) or min(resolutions) <= 0.0:
        parser.error("Resolution must be positive")
    out = args.output
    out.mkdir(parents=True, exist_ok=True)
    plan = {
        "samples": list(map(int, args.samples.split(","))),
        "resolutions_m": resolutions,
        "height_tolerance_m": 0.02,
        "width_tolerance_m": 0.03,
        "area_relative_tolerance": 0.03,
        "contour_distance_tolerance_m": 0.03,
        "scope": "Local capped meshes retaining all network sweeps; no automatic stitching into the full network.",
    }
    if args.resume and json.loads((out / "plan.json").read_text()) != plan:
        parser.error("Resume requires the identical saved study plan")
    identity = study_identity(args.checkpoint, config, anchor)
    provenance = out / "provenance.json"
    if args.resume and (not provenance.exists() or json.loads(provenance.read_text()) != identity):
        parser.error(
            "Resume requires identical checkpoint, geometry configuration and region policy"
        )
    provenance.write_text(json.dumps(identity, indent=2) + "\n")
    (out / "plan.json").write_text(json.dumps(plan, indent=2) + "\n")
    rows = []
    for index in plan["samples"]:
        s = samples[index]
        folder = out / f"sample_{index}"
        folder.mkdir(exist_ok=True)
        center = np.array([s.x, s.y, s.z])
        # A short reach with a full-width section and enough normal-filter
        # context. The box dimensions remain fixed at every resolution.
        extent = 0.5 * s.tube_width * np.abs(s.normal) + 2.0 * np.abs(s.tangent) + np.ones(3)
        contours, measures = [], []
        for h in resolutions:
            started = time.monotonic()
            destination = folder / f"voxel_{h:g}m"
            destination.mkdir(exist_ok=True)
            c = replace(
                config,
                voxel_size=h,
                storage_mode="dense",
                target_samples_across_passage=config.characteristic_passage_width_m / h,
            )
            if args.resume and (destination / "export_checks.json").exists():
                check = json.loads((destination / "export_checks.json").read_text())
                if (
                    not all(check["checks"].values())
                    or check["sha256"]
                    != hashlib.sha256(
                        (destination / "lava_tube_geometry.glb").read_bytes()
                    ).hexdigest()
                ):
                    raise ValueError(f"Cached export failed verification: {destination}")
            else:
                geometry = local_geometry(
                    network,
                    sections,
                    c,
                    center=center,
                    half_extent=extent,
                    lattice_origin=anchor,
                    max_voxels=args.max_voxels,
                )
                export_surface(
                    geometry, destination, elapsed_before_export=time.monotonic() - started
                )
                del geometry
            scene = trimesh.load(
                destination / "lava_tube_geometry.glb", force="scene", process=False
            )
            mesh = next(iter(scene.geometry.values())).copy(include_cache=True)
            mesh.apply_transform(
                np.array([[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])
            )
            bounds = np.array(
                [
                    anchor + np.floor((center - extent - anchor) / h) * h,
                    anchor + np.ceil((center + extent - anchor) / h) * h,
                ]
            )
            q = section_contour(mesh, s, region_bounds=bounds, clip_margin_m=2 * h)
            contours.append(q)
            np.save(destination / "measured_contour.npy", q)
            m = {
                "voxel_size_m": h,
                **contour_morphometry(q),
                "mesh_components": int(mesh.body_count),
                "height_in_voxels": float(np.ptp(q[:, 1]) / h),
                "vertices": len(mesh.vertices),
                "contour_clear_of_artificial_caps": True,
            }
            measures.append(m)
            print(
                f"sample {index}, {h:g} m: height {m['height_m']:.4f}, width {m['width_m']:.4f}",
                flush=True,
            )
            del mesh, scene
        a, b = measures[-2:]
        delta = {
            "height_m": abs(a["height_m"] - b["height_m"]),
            "width_m": abs(a["width_m"] - b["width_m"]),
            "relative_area": abs(a["area_m2"] - b["area_m2"]) / b["area_m2"],
            "contour_distance_m": contour_distance(contours[-2], contours[-1]),
        }
        criteria = {
            "height": delta["height_m"] <= plan["height_tolerance_m"],
            "width": delta["width_m"] <= plan["width_tolerance_m"],
            "area": delta["relative_area"] <= plan["area_relative_tolerance"],
            "contour": delta["contour_distance_m"] <= plan["contour_distance_tolerance_m"],
        }
        passed = all(criteria.values())
        row = {
            "sample_index": index,
            "sample": asdict(s),
            "measurements": measures,
            "last_refinement_difference": delta,
            "convergence_checks": criteria,
            "converged": passed,
        }
        rows.append(row)
        (folder / "measurements.json").write_text(json.dumps(row, indent=2) + "\n")
        plot_convergence(folder, index, resolutions, contours)
        complete = len(rows) == len(plan["samples"])
        (out / "summary.json").write_text(
            json.dumps(
                {
                    "plan": plan,
                    "complete": complete,
                    "all_converged": complete and all(r["converged"] for r in rows),
                    "results": rows,
                },
                indent=2,
            )
            + "\n"
        )


if __name__ == "__main__":
    main()
